# Generated by Django 3.0 on 2020-09-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id_type',
            field=models.CharField(choices=[('passport', 'passport'), ('drivers_license', 'drivers_license')], max_length=255),
        ),
    ]
