# Generated by Django 3.0 on 2020-09-05 18:58

from django.db import migrations, models
import django.db.models.deletion
import tests.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20200901_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('create_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Canceled', 'Canceled'), ('Checked in', 'Checked in'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Test_Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('number_of_stations', tests.models.PositiveTinyIntegerField()),
                ('candidates', models.ManyToManyField(related_name='test_centers', through='tests.Test', to='tests.Candidate')),
                ('exams', models.ManyToManyField(related_name='test_centers', through='tests.Test', to='tests.Exam')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='tests.Candidate'),
        ),
        migrations.AddField(
            model_name='test',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='tests.Exam'),
        ),
        migrations.AddField(
            model_name='test',
            name='test_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='tests.Test_Center'),
        ),
        migrations.AddField(
            model_name='exam',
            name='candidates',
            field=models.ManyToManyField(related_name='exams', through='tests.Test', to='tests.Candidate'),
        ),
        migrations.AddField(
            model_name='exam',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.Client'),
        ),
    ]
